### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by shadyabhi** [netgroup-polito/ebpf-test#1]
Steps to reproduce:- 

* Clone the repo.
* Run `sudo http-parse-complete.py`

```bash
 ➤ sudo python http-parse-complete.py
binding socket to 'eth0'
bpf: Failed to load program: Invalid argument

Traceback (most recent call last):
  File "http-parse-complete.py", line 122, in <module>
    function_http_filter = bpf.load_func("http_filter", BPF.SOCKET_FILTER)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 379, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program http_filter: Invalid argument
```

I'm only starting to enter the eBPF world, just did a basic check that `http_filter` indeed exists in the `.c` file.

**Comment by stokito** [comment]
`python2.7` maybe it work with python3?

**Comment by frisso** [comment]
@stokito , this repository is rather old and no longer maintained.
The code was improved and merged into bcc; I would suggest to look at https://github.com/iovisor/bcc/tree/master/examples/networking/http_filter .
